FROM debian:wheezy

#Default branch name develop
ARG BRANCH_NAME=develop
#Default
ARG REPO_SLUG=violette/violette
ENV REPO_SLUG=${REPO_SLUG}
ENV REPO_URL=https://github.com/${REPO_SLUG}

RUN apt-get -qq update && \
    apt-get -qqy install \
    git \
    sudo

#RUN git clone ${REPO_URL} --branch $BRANCH_NAME --single-branch --depth 1

COPY violette.tar.gz /violette.tar.gz
RUN tar -xvf /violette.tar.gz

#ADD . /violette
RUN cd /violette/scripts/windows-crosscompile && ./dependencies.sh
RUN cd /violette && scripts/windows-crosscompile/compile-violette.sh
